"""Generate editable, framework-free HTML. Python is authoring-only; no JS ships."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent.parent
A='assets/'
models=[
 dict(id='rx',name='RX',desc='Tinh tế trong từng chuyển động',price='3.430.000.000',type='SUV · Hybrid',cat='suv hybrid'),
 dict(id='es',name='ES',desc='Thanh lịch, theo cách của bạn',price='2.620.000.000',type='Sedan · Hybrid',cat='sedan hybrid'),
 dict(id='lx',name='LX',desc='Bản lĩnh của một biểu tượng',price='8.500.000.000',type='SUV · Xăng',cat='suv'),
 dict(id='nx',name='NX',desc='Cảm hứng cho mỗi hành trình',price='3.130.000.000',type='SUV · Hybrid',cat='suv hybrid'),
 dict(id='lm',name='LM',desc='Không gian của riêng bạn',price='7.290.000.000',type='MPV · Hybrid',cat='mpv hybrid'),
]

def image(name,alt,cls='',eager=False):
 return f'<img class="{cls}" src="assets/{name}.webp" alt="{alt}" width="1600" height="1067" '+('fetchpriority="high" loading="eager"' if eager else 'loading="lazy"')+' decoding="async">'
def btn(text,url,style=''):
 return f'<a class="button {style}" href="{url}">{text}</a>'
def link(text,url): return f'<a class="text-link" href="{url}">{text}</a>'
DEALER='Lexus Thăng Long'
ADVISOR='Thu Hà'
PHONE='0989345989'
PHONE_FMT='0989 345 989'
ZALO=f'https://zalo.me/{PHONE}'
ADDRESS='Ngã tư Phạm Hùng – Dương Đình Nghệ,<br>Cầu Giấy, Hà Nội'
MAPS='https://www.google.com/maps/search/?api=1&query=Lexus+Th%C4%83ng+Long+Ph%E1%BA%A1m+H%C3%B9ng+C%E1%BA%A7u+Gi%E1%BA%A5y+H%C3%A0+N%E1%BB%99i'
def brand(white=False):return f'<a class="brand" href="index.html" aria-label="{DEALER} — Trang chủ"><img class="brand-logo" src="assets/logo-ltl-{"white" if white else "black"}.png" alt="{DEALER}" width="1400" height="119" decoding="async"></a>'
def header(overlay=False):
 return f'''<a class="skip" href="#main">Đến nội dung chính</a><header class="site-header {'over-hero' if overlay else ''}">{brand(overlay)}<nav class="desktop-nav" aria-label="Điều hướng chính"><details><summary>Dòng xe</summary><div class="mega"><div><span class="eyebrow">Bộ sưu tập Lexus</span><a href="models.html#suv-section">SUV</a><a href="models.html#sedan-section">Sedan</a><a href="models.html#mpv-section">MPV</a><a href="models.html">Tất cả dòng xe ↗</a></div><div>{''.join(f'<a href="{m["id"]}.html">Lexus {m["name"]} <small>— {m["type"]}</small></a>' for m in models)}</div><div>{image('rx','Lexus RX trong không gian kiến trúc')}<a href="rx.html">Khám phá Lexus RX ↗</a></div></div></details><a href="bang-gia.html">Mua xe</a><a href="experience.html">Thế giới Lexus</a><a href="dich-vu.html">Dịch vụ</a><a href="tin-tuc.html">Tin tức</a></nav><a class="header-cta" href="lai-thu.html">ĐẶT LỊCH LÁI THỬ ↗</a><details class="mobile-menu"><summary><span class="menu-open">MENU ☰</span><span class="menu-close">ĐÓNG ✕</span></summary><nav aria-label="Điều hướng di động"><a href="models.html">Dòng xe Lexus</a><a href="bang-gia.html">Bảng giá & mua xe</a><a href="experience.html">Thế giới Lexus</a><a href="dich-vu.html">Dịch vụ & chăm sóc</a><a href="tin-tuc.html">Tin tức</a><a href="showroom.html">Showroom & liên hệ</a><a class="small" href="lai-thu.html">Đặt lịch lái thử ↗</a><a class="small" href="bao-gia.html">Nhận báo giá ↗</a></nav></details></header>'''
def footer():
 return f'''<footer class="site-footer"><div class="footer-top"><div class="footer-brand">{brand(True)}<p>Tinh hoa trong từng chi tiết.<br>Cảm hứng trên mọi hành trình.</p></div><div><h3>Dòng xe</h3>{''.join(f'<a href="{m["id"]}.html">Lexus {m["name"]}</a>' for m in models)}</div><div><h3>Mua xe</h3><a href="bang-gia.html">Bảng giá xe</a><a href="uu-dai.html">Đặc quyền sở hữu</a><a href="tai-chinh.html">Giải pháp tài chính</a><a href="so-sanh.html">So sánh xe</a><a href="lai-thu.html">Đăng ký lái thử</a></div><div><h3>Trải nghiệm Lexus</h3><a href="experience.html">Tinh hoa Takumi</a><a href="experience.html#omotenashi">Omotenashi</a><a href="dich-vu.html">Dịch vụ & chăm sóc</a><a href="tin-tuc.html">Câu chuyện Lexus</a></div><div><h3>Kết nối</h3><a href="showroom.html">Showroom</a><a href="lien-he.html">Liên hệ tư vấn</a><a href="tel:{PHONE}">{ADVISOR} · {PHONE_FMT}</a><a href="{ZALO}" rel="noopener">Zalo: {PHONE_FMT}</a><a href="{MAPS}" rel="noopener" target="_blank">{DEALER}, Cầu Giấy, Hà Nội</a><a href="faq.html">Câu hỏi thường gặp</a></div></div><div class="footer-bottom"><div>© 2026 {ADVISOR} · {DEALER}. Website tư vấn cá nhân của chuyên viên bán hàng, không phải website chính thức của Lexus Việt Nam.<br>Giá và ưu đãi là dữ liệu minh họa, vui lòng liên hệ để nhận thông tin cập nhật. Hình ảnh xe có thể khác phiên bản tại Việt Nam.</div><span><a href="privacy.html">Quyền riêng tư</a> &nbsp; / &nbsp; <a href="terms.html">Điều khoản</a> &nbsp; / &nbsp; <a href="components.html">Design system</a></span></div></footer>'''
def conversion():
 return f'<section class="conversion dark"><div><div class="eyebrow">Hành trình bắt đầu từ bạn</div><h2>Chạm đến trải nghiệm Lexus.</h2></div><div class="actions">{btn("Đặt lịch lái thử","lai-thu.html","light")}{link("Nhận tư vấn riêng","bao-gia.html")}</div></section>'
def sales_bar():
 return f'<nav class="sales-bar" aria-label="Tư vấn nhanh"><a href="bao-gia.html">Nhận báo giá</a><a href="tel:{PHONE}">Gọi {ADVISOR}</a><a href="{ZALO}" rel="noopener">Zalo</a></nav>'
def page(file,title,body,overlay=False,sales=False):
 html=f'''<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} | {DEALER}</title><meta name="description" content="{title}. {ADVISOR} — chuyên viên tư vấn {DEALER}, Cầu Giấy, Hà Nội. Khám phá dòng xe, báo giá và lái thử."><meta name="theme-color" content="#151617"><meta property="og:title" content="{title} | {DEALER}"><meta property="og:type" content="website"><meta property="og:description" content="{ADVISOR} — chuyên viên tư vấn {DEALER}. Khám phá dòng xe, báo giá và đặt lịch lái thử."><link rel="icon" href="assets/favicon-32.png" sizes="32x32" type="image/png"><link rel="icon" href="assets/favicon-192.png" sizes="192x192" type="image/png"><link rel="apple-touch-icon" href="assets/apple-touch-icon.png"><link rel="stylesheet" href="assets/style.css">{'<link rel="preload" as="image" href="assets/hero.webp">' if file=='index.html' else ''}</head><body class="{'has-sales' if sales else ''}">{header(overlay)}<main id="main">{body}</main>{footer()}{sales_bar() if sales else ''}</body></html>'''
 from personal_brand import update
 (ROOT/file).write_text(update(file,html))
def intro(title,desc='',eyebrow='LEXUS THĂNG LONG'):
 return f'<section class="page-intro stone"><div class="container"><div class="breadcrumb"><a href="index.html">Trang chủ</a> &nbsp; / &nbsp; {title}</div><div class="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div></section>'
def card(m):
 return f'''<article class="model-card" data-category="{m['cat']}" id="{m['id']}-card"><a class="model-image" href="{m['id']}.html">{image(m['id'],'Lexus '+m['name'])}<span class="model-label">{m['type'].upper()}</span></a><div class="model-info"><div><h3>Lexus {m['name']}</h3><p>{m['desc']}</p></div><div class="model-price"><small>GIÁ DEMO TỪ</small>{m['price']} ₫</div></div><div class="card-links"><a href="{m['id']}.html">Khám phá dòng xe ↗</a><a href="bao-gia.html">Nhận báo giá</a></div></article>'''
def catalog(home=False):
 radios=''.join(f'<input class="filter-input" type="radio" name="category" id="{id}" {"checked" if id=="all" else ""}><label for="{id}">{text}</label>' for id,text in [('all','Tất cả dòng xe'),('suv','SUV'),('sedan','Sedan'),('mpv','MPV'),('hybrid','Electrified')])
 return f'<div class="catalog"><div class="filters" aria-label="Lọc theo dòng xe">{radios}</div><div class="model-grid {"homepage-models" if home else ""}">{"".join(card(m) for m in (models[:3] if home else models))}</div></div>'
def news():
 items=[('detail','NGHỆ THUẬT CHẾ TÁC','Khi sự hoàn hảo bắt đầu từ những điều nhỏ nhất'),('interior','LEXUS EXPERIENCE','Omotenashi: sự thấu hiểu không cần lời nói'),('story','HÀNH TRÌNH','Tìm lại nhịp riêng trên những cung đường mới')]
 return '<div class="news-grid">'+''.join(f'<article class="news-card"><a href="bai-viet.html">{image(im,title)}</a><div class="meta">{tag} &nbsp; / &nbsp; 21.09.2026 · DEMO</div><h3><a href="bai-viet.html">{title}</a></h3>{link("Đọc câu chuyện","bai-viet.html")}</article>' for im,tag,title in items)+'</div>'
def contact():
 return f'<div class="contact-details"><div><span>Showroom {DEALER}</span><p>{ADDRESS}</p><a class="small" href="{MAPS}" rel="noopener" target="_blank">Chỉ đường trên Google Maps ↗</a></div><div><span>Chuyên viên tư vấn</span><p>{ADVISOR} &nbsp; — &nbsp; <a href="tel:{PHONE}">{PHONE_FMT}</a></p></div><div><span>Zalo</span><a href="{ZALO}" rel="noopener">Nhắn Zalo {PHONE_FMT} ↗</a></div><div><span>Giờ đón tiếp</span><p>Thứ Hai – Chủ Nhật &nbsp; 08:00 – 18:00</p></div></div>'
def form(kind='quote'):
 extra='<div class="field"><label for="date">Ngày lái thử mong muốn</label><input id="date" name="date" type="date" required></div><div class="field"><label for="time">Khung giờ</label><select id="time" name="time"><option>09:00 – 11:00</option><option>14:00 – 16:00</option></select></div>' if kind=='drive' else '<div class="field full"><label for="note">Lời nhắn (không bắt buộc)</label><textarea id="note" name="note" placeholder="Điều bạn mong đợi ở chiếc Lexus của mình…"></textarea></div>'
 return f'''<form class="lead-form" action="demo-success.html" method="get"><div class="field"><label for="name">Họ và tên *</label><input id="name" name="name" autocomplete="name" placeholder="Nguyễn Minh Anh" required maxlength="100"></div><div class="field"><label for="phone">Số điện thoại *</label><input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" placeholder="09xx xxx xxx" pattern="[+0-9 ().-]{{9,18}}" required></div><div class="field"><label for="model">Dòng xe quan tâm *</label><select id="model" name="model" required><option value="">Chọn dòng xe</option>{''.join('<option>Lexus '+m['name']+'</option>' for m in models)}</select></div><div class="field"><label for="location">Khu vực</label><select id="location" name="location"><option>Hà Nội</option><option>TP. Hồ Chí Minh</option><option>Tỉnh / thành khác</option></select></div>{extra}<label class="consent full"><input type="checkbox" required> <span>Tôi đã đọc <a href="privacy.html"><u>chính sách quyền riêng tư</u></a> và đồng ý với mục đích tư vấn được mô tả.</span></label><button class="button full" type="submit">Xem trạng thái đăng ký mẫu &nbsp; ↗</button><p class="form-note full">Form demo HTML/CSS, chưa gửi dữ liệu đến tư vấn viên. Chỉ nhập thông tin giả để xem mẫu xác nhận.</p></form>'''
# HOME
home=f'''<section class="hero"><picture><source media="(max-width: 600px)" srcset="assets/hero-mobile.webp">{image('hero','Lexus RX trên cung đường ven biển lúc hoàng hôn','hero-media',True)}</picture><div class="container"><div class="hero-copy"><div class="eyebrow">THE LEXUS RX · MỘT CHUẨN MỰC MỚI</div><h1>Dấu ấn riêng.<br>Hành trình khác biệt.</h1><p>Sự tĩnh tại trong từng chuyển động.<br>Tinh hoa Lexus, dành riêng cho bạn.</p><div class="actions">{btn('Khám phá Lexus RX','rx.html','light')}{link('Đặt lịch lái thử','lai-thu.html')}</div></div></div><div class="hero-bottom"><span class="hero-line">01 &nbsp; / &nbsp; THE RX COLLECTION</span><span class="hero-tag">CRAFTED FOR THE EXTRAORDINARY</span><a href="#collection">CUỘN ĐỂ KHÁM PHÁ &nbsp; ↓</a></div></section>
<div class="container intro-line"><span>LEXUS THĂNG LONG</span><span>Nghệ thuật chế tác Nhật Bản. Trải nghiệm mang dấu ấn của bạn.</span><a href="showroom.html">TÌM SHOWROOM &nbsp; ↗</a></div>
<section class="container model-discovery" id="collection"><div class="section-heading"><div><div class="eyebrow">Bộ sưu tập Lexus</div><h2>Một Lexus. Một dấu ấn riêng.</h2></div>{link('Tất cả dòng xe','models.html')}</div>{catalog(True)}<div class="section-foot"><small>Giá và phiên bản hiển thị để minh họa thiết kế.</small><a href="so-sanh.html" class="text-link">So sánh dòng xe</a></div></section>
<section class="story">{image('story','Lexus trên cung đường bên thiên nhiên')}<div class="story-content"><div class="eyebrow">THE ART OF FEELING MORE</div><h2>Không chỉ đến nơi.<br>Mà là tận hưởng.</h2><p>Để những thanh âm lắng lại. Để mỗi khúc cua đánh thức cảm hứng. Và mỗi hành trình trở thành khoảng thời gian của riêng bạn.</p><div class="actions">{link('Bước vào thế giới Lexus','experience.html')}</div></div></section>
<section class="container section"><div class="section-heading"><div><div class="eyebrow">Hành trình sở hữu</div><h2>Chiếc Lexus của bạn, từ đây.</h2></div></div><div class="shortcut-grid">{''.join(f'<a class="shortcut" href="{url}"><span class="number">0{i+1}</span><h3>{title}</h3><p>{desc}</p></a>' for i,(url,title,desc) in enumerate([('bang-gia.html','Bảng giá Lexus','Tìm lựa chọn phù hợp'),('tai-chinh.html','Giải pháp tài chính','Chủ động kế hoạch sở hữu'),('lai-thu.html','Trải nghiệm lái thử','Cảm nhận bằng mọi giác quan'),('bao-gia.html','Tư vấn dành riêng','Kết nối cùng chuyên viên')]))}</div></section>
<section class="split stone"><div class="split-media">{image('interior','Không gian nội thất Lexus và vật liệu tinh tế')}</div><div class="split-copy"><div class="eyebrow">OMOTENASHI · TẬN TÂM TỪ CHI TIẾT</div><h2>Được thấu hiểu.<br>Trước cả khi bạn nói.</h2><p>Một không gian biết đón chào. Sự êm ái vừa đủ, những chất liệu chạm đến cảm xúc. Mọi chi tiết đều bắt đầu từ bạn.</p>{link('Khám phá Omotenashi','experience.html#omotenashi')}</div></section>
<section class="split reverse"><div class="split-copy"><div class="eyebrow">TAKUMI · NGHỆ THUẬT CHẾ TÁC</div><h2>Sự tinh tế nằm ở<br>những điều rất nhỏ.</h2><p>Từ đường chỉ khâu đến bề mặt vật liệu, sự chăm chút tạo nên một vẻ đẹp không cần phô trương.</p>{link('Câu chuyện nghệ nhân','experience.html#takumi')}</div><div class="split-media">{image('detail','Chi tiết hoàn thiện và vật liệu trên Lexus')}</div></section>
<section class="section stone"><div class="container"><div class="section-heading"><div><div class="eyebrow">Đặc quyền sở hữu</div><h2>Thêm cảm hứng. Trọn an tâm.</h2></div>{link('Khám phá đặc quyền','uu-dai.html')}</div><div class="editorial-grid"><article class="editorial-card">{image('rx','Lexus RX — hành trình sở hữu')}<div class="eyebrow">TƯ VẤN SỞ HỮU</div><h3>Một kế hoạch dành riêng cho bạn.</h3><p>Khám phá các phương án tài chính minh họa và lựa chọn phù hợp với kế hoạch của bạn.</p>{link('Tìm hiểu thêm','tai-chinh.html')}</article><article class="editorial-card">{image('lx','Lexus LX — trải nghiệm chăm sóc')}<div class="eyebrow">CHĂM SÓC LEXUS</div><h3>An tâm trên mỗi chặng đường.</h3><p>Chăm sóc chu đáo từ buổi hẹn đầu tiên đến những hành trình về sau.</p>{link('Khám phá dịch vụ','dich-vu.html')}</article></div></div></section>
<section class="container section"><div class="contact-section"><div>{image('showroom','Không gian đón tiếp tại showroom Lexus')}</div><div><div class="eyebrow">MỘT LỜI MỜI DÀNH RIÊNG</div><h2>Gặp gỡ Lexus.<br>Theo cách của bạn.</h2><p style="margin-top:22px">Một cuộc hẹn thong thả. Một tách cà phê.<br>Và chiếc Lexus bạn luôn mong đợi.</p>{contact()}{link('Khám phá showroom','showroom.html')}</div></div></section>
<section class="container section" style="padding-top:0"><div class="section-heading"><div><div class="eyebrow">Góc nhìn Lexus</div><h2>Những câu chuyện truyền cảm hứng.</h2></div>{link('Tất cả câu chuyện','tin-tuc.html')}</div>{news()}</section>{conversion()}'''
page('index.html','Tinh hoa chuyển động',home,True)
page('models.html','Các dòng xe Lexus',intro('Các dòng xe Lexus','Mỗi thiết kế là một cá tính. Tìm chiếc Lexus đồng điệu với phong cách và hành trình của bạn.','THE LEXUS COLLECTION')+f'<section class="container section"><span id="suv-section"></span><span id="sedan-section"></span><span id="mpv-section"></span>{catalog()}<div class="section-foot"><small>Giá demo, không phải báo giá chính thức.</small>{link("So sánh 3 dòng xe","so-sanh.html")}</div></section><section class="split stone"><div class="split-media">{image("story","Lexus electrified trong hành trình")}</div><div class="split-copy"><div class="eyebrow">LEXUS ELECTRIFIED</div><h2>Chuyển động hôm nay.<br>Cảm hứng ngày mai.</h2><p>Khám phá một góc nhìn mới về sự êm ái và cảm giác lái qua các dòng xe Hybrid.</p>{link("Khám phá trải nghiệm","experience.html")}</div></section>'+conversion())
# MODEL DETAIL — shared template, adapted copy
for m in models:
 name=m['name'];mid=m['id'];isrx=mid=='rx'
 hero=f'''<section class="hero model-hero">{image('hero' if isrx else mid,'Lexus '+name,'hero-media',True)}<div class="container"><div class="hero-copy"><div class="eyebrow">THE LEXUS {name}</div><h1>LEXUS {name}</h1><h2>{m['desc']}.</h2><p>Giá demo từ {m['price']} ₫</p><div class="actions">{btn('Khám phá phiên bản','#versions','light')}{link('Nhận báo giá','bao-gia.html')}</div></div></div><div class="hero-bottom"><span>{m['type'].upper()}</span><a href="#overview">KHÁM PHÁ &nbsp; ↓</a></div></section>'''
 nav='<nav class="model-nav" aria-label="Nội dung dòng xe"><strong>LEXUS '+name+'</strong><div><a href="#overview">Tổng quan</a><a href="#design">Thiết kế</a><a href="#interior">Nội thất</a><a href="#gallery">Thư viện</a><a href="#versions">Phiên bản</a></div>'+btn('Báo giá','bao-gia.html')+'</nav>'
 facts=f'<div class="container spec-strip" id="overview"><div><small>PHONG CÁCH</small><strong>{m["type"].split(" · ")[0]}</strong><small>Dòng xe Lexus</small></div><div><small>TRUYỀN ĐỘNG</small><strong>{m["type"].split(" · ")[1]}</strong><small>Phiên bản minh họa</small></div><div><small>KHÔNG GIAN</small><strong>{"7" if mid=="lx" else "4 / 6" if mid=="lm" else "5"} chỗ</strong><small>Tùy cấu hình</small></div><div><small>TRẢI NGHIỆM</small><strong>Omotenashi</strong><small>Đón tiếp từ sự thấu hiểu</small></div></div>'
 design=f'<section class="split stone" id="design"><div class="split-media">{image(mid,"Ngoại thất Lexus "+name)}</div><div class="split-copy"><div class="eyebrow">01 / THIẾT KẾ NGOẠI THẤT</div><h2>Cuốn hút từ<br>ánh nhìn đầu tiên.</h2><p>Những đường nét dứt khoát gặp gỡ tỷ lệ hài hòa. Một diện mạo mang dấu ấn Lexus, hiện diện đầy tự tin trong mọi không gian.</p></div></section>'
 colors=f'''<section class="section stone"><div class="container visualizer"><div class="color-stage">{image('design03','Góc nhìn từ trên của Lexus RX','white-img')}{image('design02','Góc nhìn bên hông Lexus RX','copper-img')}{image('rx','Góc nhìn phía sau Lexus RX','black-img')}</div><div><div class="eyebrow">THIẾT KẾ TỪ MỌI GÓC NHÌN</div><h2>Một thiết kế. Nhiều cảm xúc.</h2><div class="swatches view-controls"><input id="white" type="radio" name="color" checked><label for="white" aria-label="Góc trên">01</label><input id="copper" type="radio" name="color"><label for="copper" aria-label="Góc bên">02</label><input id="black" type="radio" name="color"><label for="black" aria-label="Góc sau">03</label></div><p class="color-name white-name">01 / Đường nét từ trên cao</p><p class="color-name copper-name">02 / Tỷ lệ cân đối</p><p class="color-name black-name">03 / Dấu ấn phía sau</p><p class="small" style="margin-top:18px">Chọn một góc nhìn để khám phá thiết kế RX. Hình ảnh phiên bản minh họa.</p></div></div></section>''' if isrx else ''
 interior=f'<section class="split reverse" id="interior"><div class="split-copy"><div class="eyebrow">02 / KHÔNG GIAN NỘI THẤT</div><h2>Mở cửa.<br>Khép lại ồn ào.</h2><p>Sự tĩnh tại được tạo nên từ những điều có thể chạm tới: chất liệu tinh tế, ánh sáng dịu và cách bố trí hướng đến người sử dụng.</p><p class="small">Ảnh nội thất Lexus minh họa ngôn ngữ thiết kế; trang bị tùy dòng xe và thị trường.</p></div><div class="split-media">{image("interior","Không gian nội thất Lexus")}</div></section>'
 performance=f'<section class="story">{image("story","Lexus trên hành trình")}<div class="story-content"><div class="eyebrow">03 / CẢM GIÁC LÁI</div><h2>Êm ái để tận hưởng.<br>Hứng khởi để khám phá.</h2><p>Mỗi hành trình là một cuộc đối thoại giữa bạn, chiếc xe và con đường phía trước.</p>{link("Trực tiếp cảm nhận","lai-thu.html")}</div></section>'
 tech='<section class="container section"><div class="section-heading"><div><div class="eyebrow">04 / CÔNG NGHỆ & AN TÂM</div><h2>Thông minh một cách tự nhiên.</h2></div><p>Những tiện ích đặt trải nghiệm của người lái ở trung tâm. Trang bị cụ thể cần xác nhận theo phiên bản.</p></div><div class="accordion">'+''.join(f'<details {"open" if i==0 else ""}><summary>{title}</summary><p>{text}</p></details>' for i,(title,text) in enumerate([('Khoang lái hướng đến người lái','Các thao tác được bố trí trong tầm tay, giúp bạn tập trung hơn vào hành trình và tận hưởng không gian xung quanh.'),('Kết nối và giải trí','Không gian giải trí được cân nhắc cùng sự tiện lợi trong sử dụng hàng ngày. Vui lòng xác nhận khả năng tương thích và trang bị với chuyên viên.'),('Hỗ trợ lái & an toàn','Các hệ thống hỗ trợ không thay thế sự tập trung của người lái. Phạm vi hoạt động và trang bị khác nhau theo phiên bản.'),('Chất liệu & nghệ thuật Takumi','Cảm hứng thủ công thể hiện trong sự hòa hợp của chất liệu, bề mặt và chi tiết hoàn thiện. Khám phá chất liệu trực tiếp khi đến showroom.')]))+'</div></section>'
 gallery_items=[mid,'interior','detail','story','rx','lx','es','showroom']
 gallery='<section class="container section" id="gallery" style="padding-top:0"><div class="section-heading"><div><div class="eyebrow">05 / GÓC NHÌN LEXUS</div><h2>Mọi góc nhìn. Đều đáng nhớ.</h2></div><p class="small">Bộ ảnh Lexus minh họa cảm hứng thiết kế.</p></div><div class="gallery-grid">'+''.join(f'<a href="#photo-{i}" aria-label="Mở ảnh Lexus {i+1}">{image(im,"Góc nhìn Lexus "+str(i+1))}</a>' for i,im in enumerate(gallery_items))+'</div></section>'+''.join(f'<div class="lightbox" id="photo-{i}" role="region" aria-label="Ảnh Lexus phóng lớn"><a class="close" href="#gallery" aria-label="Đóng ảnh">×</a>{image(im,"Ảnh Lexus phóng lớn "+str(i+1))}</div>' for i,im in enumerate(gallery_items))
 variants=f'<section class="section stone" id="versions"><div class="container"><div class="section-heading"><div><div class="eyebrow">06 / LỰA CHỌN PHIÊN BẢN</div><h2>Phù hợp với điều bạn tìm kiếm.</h2></div><p class="small">Cấu hình & giá demo để duyệt template. Không phải cam kết bán hàng.</p></div><div class="variant-grid">'+''.join(f'<article class="variant"><div class="eyebrow">{label}</div><h3>Lexus {name} {v}</h3><p class="price">{price} ₫</p><ul><li>{power}</li><li>Không gian tinh tế</li><li>Tư vấn cấu hình riêng</li></ul>{btn("Khám phá phiên bản","phien-ban.html")}</article>' for label,v,price,power in [('THANH LỊCH','350h',m['price'],'Hybrid · cấu hình minh họa'),('TINH TẾ','Luxury','4.330.000.000','Trang bị nâng cao · minh họa'),('CÁ TÍNH','F SPORT','4.940.000.000','Phong cách thể thao · minh họa')])+'</div></div></section>' if isrx else f'<section class="container section" id="versions"><div class="eyebrow">LỰA CHỌN PHIÊN BẢN</div><h2>Lexus {name}, theo phong cách của bạn.</h2><p style="margin-top:22px">Giá minh họa từ {m["price"]} ₫. Hãy trao đổi với chuyên viên để chọn phiên bản phù hợp.</p><div class="actions">{btn("Nhận tư vấn phiên bản","bao-gia.html")}</div></section>'
 specs='<section class="container section"><div class="section-heading"><div><div class="eyebrow">07 / THÔNG TIN SỞ HỮU</div><h2>Tìm hiểu kỹ hơn.</h2></div></div><div class="accordion"><details><summary>Kích thước & không gian</summary><p>Template dành cho thông số chiều dài, chiều rộng, chiều cao, chiều dài cơ sở và dung tích khoang hành lý. Dữ liệu kỹ thuật chính thức sẽ được cập nhật theo phiên bản và thị trường.</p></details><details><summary>Động cơ & vận hành</summary><p>Vui lòng trao đổi với chuyên viên để xác nhận động cơ, công suất và hệ dẫn động của chiếc xe bạn quan tâm.</p></details><details><summary>Bảo hành & chăm sóc</summary><p>Chính sách bảo hành, điều kiện bảo dưỡng và hỗ trợ cần được xác nhận trong báo giá chính thức. <a href="dich-vu.html"><u>Xem trải nghiệm chăm sóc</u></a>.</p></details></div><div class="notice">Cần một kế hoạch sở hữu phù hợp? <a href="tai-chinh.html"><u>Khám phá phương án tài chính minh họa ↗</u></a></div></section>'
 lead=f'<section class="section stone"><div class="container lead-layout"><div class="lead-copy"><div class="eyebrow">MỘT BƯỚC ĐẾN GẦN HƠN</div><h2>Lexus {name}.<br>Dành riêng cho bạn.</h2><p>Chọn dòng xe bạn quan tâm và để lại mong muốn. Một cuộc trò chuyện là khởi đầu cho hành trình mới.</p><div class="actions">{link("Đăng ký lái thử","lai-thu.html")}</div></div>{form()}</div></section>'
 related=f'<section class="container section"><div class="section-heading"><h2>Tiếp tục khám phá.</h2>{link("Tất cả dòng xe","models.html")}</div><div class="model-grid">'+''.join(card(x) for x in models if x['id']!=mid)[:0]+'</div></section>'
 related=f'<section class="container section"><div class="section-heading"><h2>Tiếp tục khám phá.</h2>{link("Tất cả dòng xe","models.html")}</div><div class="model-grid">'+''.join(card(x) for x in [x for x in models if x['id']!=mid][:3])+'</div></section>'
 page(mid+'.html','Lexus '+name,hero+nav+facts+design+colors+interior+performance+tech+gallery+variants+specs+lead+related,True,True)
# SALES AND CONTACT
for file,title,desc,kind in [('bao-gia.html','Một báo giá. Dành riêng cho bạn.','Tìm hiểu lựa chọn, phiên bản và kế hoạch sở hữu phù hợp.','quote'),('lai-thu.html','Cảm nhận Lexus. Bằng chính bạn.','Chọn một khoảng thời gian thư thái để khám phá chiếc Lexus bạn yêu thích.','drive'),('lien-he.html','Bắt đầu một cuộc trò chuyện.','Chúng tôi luôn dành thời gian lắng nghe điều bạn mong đợi.','quote')]:
 page(file,title,intro(title,desc,'KẾT NỐI CÙNG LEXUS')+f'<section class="container section"><div class="lead-layout"><div class="lead-copy"><div class="eyebrow">TƯ VẤN CÁ NHÂN</div><h2>Hân hạnh<br>được đón tiếp bạn.</h2>{contact()}<div id="zalo" class="notice">Zalo: <a href="{ZALO}" rel="noopener"><u>{PHONE_FMT}</u></a> — nhắn tin trực tiếp cho {ADVISOR}, phản hồi trong giờ làm việc.</div></div>{form(kind)}</div></section>')
page('demo-success.html','Trạng thái đăng ký mẫu','<section class="state-page center"><div><div class="eyebrow">GIAO DIỆN XÁC NHẬN · DEMO</div><div class="state-number">✓</div><h1>Cảm ơn bạn đã trải nghiệm.</h1><p>Đây là mẫu màn hình xác nhận. Chưa có yêu cầu nào được gửi hoặc lưu trên máy chủ.</p><div class="notice">Mã mẫu: LX-DEMO-0001<br>Thời gian phản hồi dự kiến khi triển khai thực tế: trong 1 ngày làm việc.</div><div class="actions">'+btn('Về trang chủ','index.html')+link('Thông tin liên hệ','lien-he.html')+'</div></div></section>')
page('bang-gia.html','Bảng giá Lexus',intro('Khởi đầu hành trình sở hữu.','Khám phá các dòng xe và mức giá minh họa trong bộ template.','BẢNG GIÁ LEXUS')+'<section class="container section"><div class="section-heading"><h2>Bảng giá tham khảo</h2><span class="demo-label">Dữ liệu demo · 21.09.2026</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Dòng xe</th><th>Phong cách</th><th>Giá demo từ</th><th>Tư vấn</th></tr></thead><tbody>'+''.join(f'<tr><td><a href="{m["id"]}.html">Lexus {m["name"]}</a></td><td>{m["type"]}</td><td>{m["price"]} ₫</td><td>{link("Báo giá","bao-gia.html")}</td></tr>' for m in models)+'</tbody></table></div><p class="notice">Giá trên chỉ dùng để minh họa bố cục, không phải giá niêm yết hiện hành. Không bao gồm chi phí lăn bánh và tùy chọn. Giá bán thực tế cần được xác nhận với đơn vị bán xe.</p><div class="actions">'+btn('Ước tính chi phí lăn bánh','lan-banh.html')+link('Giải pháp tài chính','tai-chinh.html')+'</div></section>'+conversion())
page('so-sanh.html','So sánh dòng xe',intro('Đặt những lựa chọn cạnh nhau.','Một góc nhìn rõ ràng hơn trước khi chọn chiếc Lexus của bạn. Bộ so sánh mẫu gồm RX, ES và LX.','SO SÁNH LEXUS')+'<section class="container section comparison"><div class="compare-grid">'+''.join(f'<article>{image(m["id"],"Lexus "+m["name"])}<h3>Lexus {m["name"]}</h3><p>{m["price"]} ₫ · Demo</p>{link("Khám phá",m["id"]+".html")}</article>' for m in models[:3])+'</div><label class="compare-toggle"><input id="different" type="checkbox"> Chỉ hiện điểm khác nhau</label><div class="table-wrap"><table class="data-table"><thead><tr><th>Tiêu chí</th><th>Lexus RX</th><th>Lexus ES</th><th>Lexus LX</th></tr></thead><tbody><tr><td>Kiểu dáng</td><td>SUV</td><td>Sedan</td><td>SUV</td></tr><tr><td>Hệ truyền động mẫu</td><td>Hybrid</td><td>Hybrid</td><td>Xăng</td></tr><tr><td>Số chỗ mẫu</td><td>5</td><td>5</td><td>7</td></tr><tr><td>Phong cách</td><td>Linh hoạt, tinh tế</td><td>Thanh lịch, thư thái</td><td>Rộng rãi, mạnh mẽ</td></tr><tr class="same"><td>Tư vấn cá nhân</td><td>Có</td><td>Có</td><td>Có</td></tr><tr class="same"><td>Đăng ký lái thử</td><td>Có</td><td>Có</td><td>Có</td></tr></tbody></table></div><p class="notice">Bảng cấu hình cố định để duyệt template. Trên điện thoại có thể cuộn ngang bảng. Thông số và giá cần xác nhận theo phiên bản thực tế.</p></section>'+conversion())
# FINANCE — deliberately static assumptions, no fake live calculator
for file,title,onroad in [('tai-chinh.html','Chủ động kế hoạch sở hữu.',False),('lan-banh.html','Dự tính cho hành trình mới.',True)]:
 fields='<div class="field full"><label for="vehicle">Dòng xe minh họa</label><input id="vehicle" value="Lexus RX · giá demo 3.430.000.000 ₫" readonly></div>'
 fields+=('<div class="field"><label for="region">Khu vực giả định</label><input id="region" value="Hà Nội" readonly></div><div class="field"><label for="tax">Trước bạ giả định</label><input id="tax" value="10%" readonly></div>' if onroad else '<div class="field"><label for="deposit">Trả trước giả định</label><input id="deposit" value="30%" readonly></div><div class="field"><label for="term">Kỳ hạn giả định</label><input id="term" value="60 tháng" readonly></div><div class="field full"><label for="rate">Lãi suất cố định giả định</label><input id="rate" value="8% / năm" readonly></div>')
 rows=([('Giá xe demo','3.430.000.000 ₫'),('Trước bạ giả định · 10%','343.000.000 ₫'),('Biển số giả định','20.000.000 ₫'),('Chi phí khác giả định','5.000.000 ₫')] if onroad else [('Trả trước · 30%','1.029.000.000 ₫'),('Khoản vay minh họa','2.401.000.000 ₫'),('Kỳ hạn','60 tháng'),('Lãi suất giả định','8% / năm')])
 body=intro(title,'Một ví dụ minh họa để bạn hình dung kế hoạch tài chính. Các giá trị chưa phải điều kiện giao dịch thực tế.','ƯỚC TÍNH CHI PHÍ' if onroad else 'GIẢI PHÁP TÀI CHÍNH')+f'<section class="container section"><div class="finance-layout"><div><div class="eyebrow">THÔNG SỐ GIẢ ĐỊNH</div><h2>{"Chi phí lăn bánh mẫu" if onroad else "Phương án trả góp mẫu"}</h2><p style="margin:20px 0 30px">Mẫu giao diện HTML/CSS với một phương án cố định. Bộ tính tương tác sẽ được kết nối ở giai đoạn phát triển chức năng.</p><div class="finance-form">{fields}</div><p class="notice">Dữ liệu demo ngày 21.09.2026. {"Các mức phí là số giả định để trình bày giao diện, không đại diện quy định hiện hành." if onroad else "Ví dụ dùng phương pháp trả góp đều: khoản vay × lãi suất tháng / [1 − (1 + lãi suất tháng)⁻⁶⁰]. Chưa tính phí hay bảo hiểm khoản vay."}</p></div><aside class="estimate"><div class="eyebrow">KẾT QUẢ ƯỚC TÍNH · DEMO</div><p>{"Tổng chi phí giả định" if onroad else "Khoản trả góp mỗi tháng"}</p><div class="result">{"3,798 tỷ" if onroad else "48,68 triệu"} <span style="font-size:16px">₫</span></div><dl>'+''.join(f'<div><dt>{k}</dt><dd>{v}</dd></div>' for k,v in rows)+f'</dl>{btn("Nhận phương án riêng","bao-gia.html")}<p class="small" style="margin-top:20px">Không phải lời chào cấp tín dụng hoặc báo giá. Điều kiện thực tế do đơn vị cung cấp xác nhận.</p></aside></div></section>'+conversion()
 page(file,title,body)
page('uu-dai.html','Đặc quyền sở hữu',intro('Để trải nghiệm thêm trọn vẹn.','Những lời mời dành cho hành trình Lexus của bạn. Nội dung chương trình dưới đây là mẫu thiết kế.','ĐẶC QUYỀN SỞ HỮU')+f'<section class="container section"><div class="editorial-grid"><article class="editorial-card">{image("rx","Lexus RX")}<div class="eyebrow">CHƯƠNG TRÌNH MẪU · THÁNG 09/2026</div><h3>Buổi hẹn khám phá Lexus RX.</h3><p>Trải nghiệm không gian, thiết kế và cảm giác lái theo lịch hẹn cá nhân.</p>{link("Chi tiết chương trình","chi-tiet-uu-dai.html")}</article><article class="editorial-card">{image("interior","Nội thất Lexus")}<div class="eyebrow">DỊCH VỤ CÁ NHÂN</div><h3>Tư vấn lựa chọn dành riêng.</h3><p>Dành thời gian tìm hiểu màu sắc, chất liệu và phương án sở hữu.</p>{link("Đặt lịch tư vấn","lien-he.html")}</article></div><p class="notice">Các chương trình minh họa không tạo quyền lợi hoặc ưu đãi thực tế. Vui lòng thay bằng nội dung đã được phê duyệt trước khi công bố.</p></section>'+conversion())
page('chi-tiet-uu-dai.html','Buổi hẹn cùng Lexus RX',intro('Một buổi hẹn. Nhiều cảm hứng.','Khám phá Lexus RX trong không gian và thời gian dành riêng cho bạn.','CHƯƠNG TRÌNH MẪU')+image('rx','Lexus RX')+'<article class="article"><div class="eyebrow">MẪU NỘI DUNG CHƯƠNG TRÌNH</div><h2>Trải nghiệm theo nhịp riêng.</h2><p>Buổi hẹn mẫu gồm giới thiệu thiết kế, khám phá khoang nội thất và trao đổi về nhu cầu sử dụng. Lịch lái thử cần được showroom xác nhận.</p><h2>Thông tin minh họa</h2><p>Thời gian mẫu: 01–30.09.2026. Dòng xe: Lexus RX. Địa điểm: showroom Lexus Thăng Long, Cầu Giấy, Hà Nội.</p><p>Đây không phải chương trình đang mở đăng ký thực tế và không kèm cam kết ưu đãi.</p>'+btn('Xem form đăng ký mẫu','lai-thu.html')+'</article>')
page('phien-ban.html','Lexus RX 350h',f'<section class="hero model-hero">{image("rx","Lexus RX 350h","hero-media",True)}<div class="container"><div class="eyebrow">THE LEXUS RX · PHIÊN BẢN MẪU</div><h1>RX 350h</h1><p>Hybrid. Tinh tế và đầy cảm hứng.</p><div class="actions">{btn("Nhận báo giá","bao-gia.html","light")}{link("Xem dòng RX","rx.html")}</div></div></section><section class="container section"><div class="section-heading"><div><div class="eyebrow">MỘT LỰA CHỌN CÂN BẰNG</div><h2>Đồng điệu với mỗi ngày.</h2></div><p>Trang mẫu cho phiên bản RX 350h. Giá, trang bị và cấu hình cần được cập nhật theo dữ liệu chính thức.</p></div><div class="spec-strip"><div><small>PHIÊN BẢN</small><strong>350h</strong></div><div><small>ĐỘNG LỰC</small><strong>Hybrid</strong></div><div><small>KHÔNG GIAN MẪU</small><strong>5 chỗ</strong></div><div><small>GIÁ DEMO</small><strong>3,43 tỷ ₫</strong></div></div></section><section class="split stone"><div class="split-media">{image("interior","Nội thất Lexus minh họa")}</div><div class="split-copy"><div class="eyebrow">DÀNH CHO BẠN</div><h2>Khám phá trực tiếp.<br>Lựa chọn tự tin.</h2><p>Trải nghiệm chất liệu, tư thế ngồi và không gian thực tế tại buổi hẹn cá nhân.</p>{link("Đặt lịch lái thử","lai-thu.html")}</div></section>'+conversion(),True,True)
# EDITORIAL / BRAND
page('experience.html','Thế giới Lexus',f'<section class="hero compact-hero">{image("detail","Nghệ thuật hoàn thiện Lexus","hero-media",True)}<div class="container"><div class="eyebrow">THE LEXUS WAY</div><h1>Vẻ đẹp của<br>sự tận tâm.</h1></div></section><section class="container section"><div class="section-heading"><div><div class="eyebrow">TRIẾT LÝ LEXUS</div><h2>Chạm đến cảm xúc.<br>Từ những điều giản dị.</h2></div><p>Một góc nhìn về sự sang trọng: chất liệu được chăm chút, chuyển động hài hòa và cảm giác được đón tiếp.</p></div></section><section class="split stone" id="takumi"><div class="split-media">{image("detail","Chi tiết chế tác Lexus")}</div><div class="split-copy"><div class="eyebrow">01 / TAKUMI</div><h2>Đôi tay.<br>Đôi mắt. Trái tim.</h2><p>Vẻ đẹp của chế tác nằm trong cách từng chi tiết được quan sát và hoàn thiện. Đó là sự kiên nhẫn dành cho những điều nhỏ nhất.</p>{link("Câu chuyện chế tác","bai-viet.html")}</div></section><section class="split reverse" id="omotenashi"><div class="split-copy"><div class="eyebrow">02 / OMOTENASHI</div><h2>Mỗi vị khách.<br>Một sự thấu hiểu.</h2><p>Tinh thần hiếu khách bắt đầu bằng việc lắng nghe. Từ một cuộc hẹn riêng đến không gian êm dịu, mọi trải nghiệm đều hướng đến sự thoải mái của bạn.</p>{link("Ghé thăm showroom","showroom.html")}</div><div class="split-media">{image("interior","Không gian nội thất Lexus")}</div></section><section class="story">{image("story","Hành trình Lexus")}<div class="story-content"><div class="eyebrow">03 / LEXUS ELECTRIFIED</div><h2>Năng lượng mới.<br>Cảm hứng vẹn nguyên.</h2><p>Một cách cảm nhận mới về chuyển động. Khám phá các dòng xe Hybrid và tìm lựa chọn cho hành trình của mình.</p>{link("Khám phá dòng xe","models.html")}</div></section>'+conversion(),True)
page('tin-tuc.html','Góc nhìn Lexus',intro('Những câu chuyện đáng dành thời gian.','Thiết kế, con người và những trải nghiệm làm nên một góc nhìn Lexus.','LEXUS JOURNAL')+f'<section class="container section"><div class="editorial-grid" style="align-items:center"><a href="bai-viet.html">{image("detail","Nghệ thuật hoàn thiện Lexus")}</a><div><div class="eyebrow">CÂU CHUYỆN NỔI BẬT</div><h2>Sự hoàn hảo bắt đầu<br>từ những điều nhỏ nhất.</h2><p style="margin-top:22px">Một góc nhìn về chất liệu, đường nét và sự chăm chút trong thiết kế.</p>{link("Đọc câu chuyện","bai-viet.html")}</div></div></section><section class="container section" style="padding-top:0">{news()}</section>'+conversion())
page('bai-viet.html','Sự tinh tế trong từng chi tiết',intro('Sự tinh tế trong từng chi tiết.','Một góc nhìn về nghệ thuật chế tác, nơi cảm xúc bắt đầu từ những điều có thể chạm tới.','LEXUS JOURNAL · BÀI VIẾT DEMO · 21.09.2026')+image('detail','Chi tiết vật liệu Lexus')+f'<article class="article"><p>Một chiếc xe được cảm nhận theo nhiều cách. Từ ánh nhìn đầu tiên đến lúc đặt tay lên vô-lăng, những ấn tượng nhỏ dần kết nối thành một trải nghiệm trọn vẹn.</p><h2>Vật liệu kể câu chuyện riêng.</h2><p>Ánh sáng lướt qua bề mặt, một đường chỉ khâu gọn gàng hay cảm giác khi chạm vào chất liệu đều góp phần tạo nên không gian. Sự sang trọng có thể hiện diện trong chính những điều giản dị ấy.</p><figure>{image("interior","Không gian Lexus")}<figcaption>Nội thất Lexus minh họa. Cấu hình khác nhau theo mẫu xe và thị trường.</figcaption></figure><h2>Khoảng lặng trên mỗi hành trình.</h2><p>Trong một ngày nhiều chuyển động, khoang xe có thể trở thành nơi để tìm lại nhịp riêng. Cách bố trí, ánh sáng và sự thuận tiện cùng tạo nên cảm giác dễ chịu.</p><blockquote>Đôi khi, điều đáng nhớ nhất là cảm giác mọi thứ đã được nghĩ đến.</blockquote><h2>Cảm nhận bằng chính bạn.</h2><p>Hình ảnh chỉ kể một phần câu chuyện. Một cuộc hẹn tại showroom là cơ hội để bạn tự cảm nhận chất liệu, không gian và lựa chọn phù hợp.</p>{link("Khám phá Lexus RX","rx.html")}</article>'+conversion())
page('showroom.html','Showroom & tư vấn',f'<section class="hero compact-hero">{image("showroom","Không gian showroom Lexus","hero-media",True)}<div class="container"><div class="eyebrow">WELCOME TO YOUR LEXUS EXPERIENCE</div><h1>Một không gian.<br>Dành để đón bạn.</h1></div></section><section class="container section"><div class="contact-section"><div><div class="eyebrow">LEXUS THĂNG LONG · CẦU GIẤY, HÀ NỘI</div><h2>Hân hạnh được<br>đồng hành cùng bạn.</h2>{contact()}<div class="actions">{btn("Đặt lịch hẹn","lien-he.html")}{link("Tư vấn trực tiếp","bao-gia.html")}</div></div>{image("interior","Không gian trải nghiệm Lexus")}</div></section><section class="section stone"><div class="container"><div class="section-heading"><h2>Mỗi cuộc hẹn đều có ý nghĩa.</h2></div><div class="shortcut-grid"><div class="shortcut"><span class="number">01</span><h3>Khám phá xe</h3><p>Tìm hiểu thiết kế & không gian</p></div><div class="shortcut"><span class="number">02</span><h3>Lái thử</h3><p>Cảm nhận thực tế theo lịch hẹn</p></div><div class="shortcut"><span class="number">03</span><h3>Tư vấn riêng</h3><p>Lựa chọn cấu hình phù hợp</p></div><div class="shortcut"><span class="number">04</span><h3>Chăm sóc</h3><p>Đồng hành sau mỗi hành trình</p></div></div></div></section>'+conversion(),True)
page('dich-vu.html','Dịch vụ & chăm sóc',intro('An tâm, trên mỗi chặng đường.','Sự quan tâm tiếp nối sau buổi gặp đầu tiên. Khám phá trải nghiệm chăm sóc dành cho chủ xe.','LEXUS OWNERSHIP')+f'<section class="split"><div class="split-media">{image("detail","Chăm chút từng chi tiết Lexus")}</div><div class="split-copy"><div class="eyebrow">CHĂM SÓC TẬN TÂM</div><h2>Luôn có người<br>lắng nghe bạn.</h2><p>Đặt lịch trao đổi về bảo dưỡng, kiểm tra xe và nhu cầu chăm sóc. Các dịch vụ và chính sách sẽ được đơn vị triển khai xác nhận.</p>{link("Đặt lịch tư vấn dịch vụ","lien-he.html")}</div></section><section class="container section"><div class="accordion"><details open><summary>Bảo dưỡng theo lịch hẹn</summary><p>Chuyên viên tư vấn sẽ hướng dẫn kế hoạch bảo dưỡng phù hợp với xe và lịch trình sử dụng của bạn.</p></details><details><summary>Chính sách bảo hành</summary><p>Phạm vi và điều kiện bảo hành cần căn cứ vào hồ sơ xe, phiên bản và chính sách chính thức tại thời điểm mua.</p></details><details><summary>Hỗ trợ chủ xe</summary><p>Liên hệ đơn vị bán xe để được hướng dẫn kênh hỗ trợ thực tế. Hotline trên template hiện là số demo.</p></details></div></section>'+conversion())
faqs=[('Tôi có thể đặt lịch lái thử như thế nào?','Chọn trang Đăng ký lái thử, điền thông tin mẫu và xem giao diện xác nhận. Template này chưa kết nối hệ thống tiếp nhận lịch hẹn.'),('Giá hiển thị có phải giá bán hiện hành không?','Không. Giá và cấu hình được sử dụng để minh họa thiết kế. Giá bán thực tế phải được xác nhận bằng báo giá chính thức.'),('Các hình ảnh có đúng phiên bản Việt Nam không?','Ảnh minh họa được lấy từ nguồn Lexus ở nhiều thị trường. Màu sắc và trang bị có thể khác xe phân phối tại Việt Nam.'),('Thông tin của tôi có được gửi đi không?','Template HTML/CSS chưa có máy chủ xử lý form. Không nhập thông tin thật. Biểu mẫu chỉ chuyển sang một trang xác nhận mẫu.'),('Có thể tư vấn qua Zalo không?','Khu vực liên hệ đã có vị trí dành cho Zalo; số demo chưa kết nối tài khoản. Khi triển khai sẽ thay bằng đường dẫn chính thức.')]
page('faq.html','Câu hỏi thường gặp',intro('Những điều bạn muốn biết.','','HỖ TRỢ')+'<section class="container section"><div class="accordion">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in faqs)+'</div></section>'+conversion())
page('privacy.html','Quyền riêng tư',intro('Thông tin về quyền riêng tư.','','TEMPLATE DEMO')+'<article class="article"><h2>Phạm vi bản demo</h2><p>Website này là mẫu HTML/CSS cục bộ. Không có hệ thống tài khoản, công cụ phân tích hoặc dịch vụ tiếp nhận thông tin được tích hợp.</p><h2>Biểu mẫu minh họa</h2><p>Chỉ sử dụng thông tin giả để kiểm tra bố cục và trạng thái. Khi bấm nút, trình duyệt chuyển sang trang demo; dữ liệu không được gửi cho tư vấn viên. Các trường có thể xuất hiện trong URL và lịch sử trình duyệt.</p><h2>Khi đưa vào sử dụng</h2><p>Đơn vị vận hành cần thay nội dung này bằng chính sách thực tế, xác định chủ thể xử lý, mục đích thu thập, thời hạn lưu giữ và cách người dùng thực hiện quyền đối với dữ liệu.</p></article>')
page('terms.html','Điều khoản sử dụng',intro('Điều khoản bản thiết kế.','','TEMPLATE DEMO')+'<article class="article"><h2>Website minh họa</h2><p>Đây là bản thiết kế độc lập để đánh giá giao diện, không đại diện cho Lexus hoặc một đại lý được ủy quyền.</p><h2>Nội dung tham khảo</h2><p>Giá, liên hệ, chương trình và phương án tài chính đều là dữ liệu demo. Không có giao dịch hoặc dịch vụ thực tế được xác lập qua bản thiết kế này.</p><h2>Hình ảnh và thương hiệu</h2><p>Lexus và các hình ảnh xe thuộc chủ sở hữu tương ứng. Cần xác nhận quyền sử dụng hình ảnh, thương hiệu và thông tin thương mại trước khi công bố website.</p></article>')
page('404.html','Không tìm thấy trang','<section class="state-page center"><div><div class="eyebrow">MỘT LỐI RẼ KHÁC</div><div class="state-number">404</div><h1>Hành trình vẫn còn phía trước.</h1><p>Trang bạn tìm kiếm không có ở đây. Hãy trở về bộ sưu tập để tiếp tục khám phá.</p><div class="actions">'+btn('Khám phá dòng xe','models.html')+link('Về trang chủ','index.html')+'</div></div></section>')
page('components.html','Design system',intro('Quiet luxury. Trong từng thành phần.','Thư viện nền tảng dùng chung cho toàn bộ template HTML/CSS.','LEXUS DESIGN SYSTEM')+'<section class="container section"><div class="eyebrow">01 / BẢNG MÀU</div><div class="token-grid">'+''.join(f'<div><div class="token-swatch" style="background:{color}"></div><strong>{name}</strong><p class="small">{color}</p></div>' for name,color in [('Ink','#151617'),('Stone','#F3F1ED'),('Paper','#FFFFFF'),('Bronze','#8B7355'),('Line','#D9D7D2')])+'</div><div style="margin-top:65px"><div class="eyebrow">02 / TYPOGRAPHY</div><h1>Tinh hoa chuyển động.</h1><h2 style="margin-top:30px">Một Lexus. Một dấu ấn riêng.</h2><p style="margin-top:25px">NobelVnu Book. Nội dung 16px, tiêu đề co giãn theo màn hình, đường nét thanh thoát.</p></div><div style="margin-top:65px"><div class="eyebrow">03 / HÀNH ĐỘNG</div><div class="actions">'+btn('Nút chính','bao-gia.html')+btn('Nút phụ','lai-thu.html','outline')+link('Liên kết văn bản','models.html')+'</div></div></section><section class="section stone"><div class="container lead-layout"><div><div class="eyebrow">04 / FORM & NATIVE STATES</div><h2>Rõ ràng. Dễ sử dụng.</h2><p style="margin-top:20px">Nhãn thật, trường bắt buộc, kiểm tra dữ liệu bằng trình duyệt và liên kết tới trạng thái mẫu.</p></div>'+form()+'</div></section>')
(ROOT/'assets/models-demo.json').write_text(json.dumps(models,ensure_ascii=False,indent=2))
print('Generated',len(list(ROOT.glob('*.html'))),'HTML pages.')
